### ISSUE TITLE
Support for APIs running on background threads

### ISSUE THREAD

**Issue by clioharp** [wix/react-native-invoke#4]
Hey guys,
I just discovered this project and haven't tried it yet. I did my own integration with an API that launches UI elements but also tries to execute background tasks such as fetching data. The issue I'm having is that some background tasks are not executing properly and as a result, some methods are returning error. I'm wondering if you've run into that issue at all with react-native-invoke/how you dealt with processes that need to run in the background.

**Comment by rotemmiz** [comment]
Hey @clioharp, I'm not sure I fully understand your use case, so please elaborate, it'll be best if you show a code snippet.

Anyway, regarding Android, currently we execute exclusively on the main thread (even though native modules are running on mqt_native_modules thread by default), and the purpose is solely for having direct access to views. We did not try executing long running tasks with invoke just yet,and that's why I'd love to understand what you're trying to do.

**Comment by clioharp** [comment]
Hi @rotemmiz, I actually just finished done getting an SDK integrated for iOS and am working on the Android integration right now. As it turns out, long running processes (at least in iOS) run fine in the background as long as you specify as much, even though views have to be called in the UI thread. I'll follow up here when I'm done with the Android with results and performance if you're interested.

**Comment by rotemmiz** [comment]
@clioharp not sure I follow. What is the specific issue/feature you're asking for here?

**Comment by rotemmiz** [comment]
I'm not sure how to continue here, closing the issue.
